[pytest]
strict = true
minversion = "9.0"
addopts = ['-v', '-m', 'not slow']
testpaths = ["tests"]
python_files = ["test_*.py"]
tmp_path_retention_policy = "failed"
markers = [
	"slow: slow tests",
	"reflink",
	"xattr",
	"manpage",
]
