#!/usr/bin/env python
# encoding: utf-8

Import('env')
Import('program')


import subprocess


def run_tests(target = None, source = None, env = None) :
    Exit(subprocess.call('nosetests', env=env['ENV'], shell=True))


if 'test' in COMMAND_LINE_TARGETS:
    test_cmd = env.Command('run_tests', None, Action(run_tests, "Running tests"))
    target = env.Depends(test_cmd, [program])
    env.Alias('test', [target])
