#!/usr/bin/env python
# encoding: utf-8

import os


Import('env')


def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file

    return None

PYTHON = ARGUMENTS.get('PYTHON', 'python3')

if 'install' in COMMAND_LINE_TARGETS and GetOption('with_gui'):
    python_exe = which(PYTHON)
    if not python_exe:
        print('!! Unable to find {} executable.'.format(PYTHON))
        print('!! Will build no GUI.')
    else:
        py_install = env.Command(
            'always.install',
            ['setup.py'],
            'cd gui && {} setup.py install --prefix {} --record .files.txt'.format(
                python_exe,
                GetOption('prefix')
            )
        )
        env.Alias('install', py_install)


if 'uninstall' in COMMAND_LINE_TARGETS and GetOption('with_gui'):
    def uninstall_python_module(**kwargs):
        try:
            with open('gui/.files.txt') as handle:
                for path in handle:
                    path = path.strip()
                    try:
                        os.remove(path)
                    except OSError as err:
                        print('Unable to delete', path, ':', err)
        except OSError as err:
            print('Could not open .files.txt: ', err)


    env.Alias('uninstall',
        env.Command(
            'gui/.files.txt', '',
            Action(uninstall_python_module , "Uninstalling recorded files...")
        )
    )
