#!/usr/bin/env python3
"""Build-time hooks:

* resolve version
* compile the GResource bundle during the build
"""

import subprocess
from pathlib import Path

from setuptools import Command, setup
from setuptools.command.build import build

GUI = Path(__file__).parent
SHREDDER = GUI / 'shredder'
RESOURCE_DIR = SHREDDER / 'resources'
GRESOURCE_XML = RESOURCE_DIR / 'shredder.gresource.xml'
GRESOURCE = RESOURCE_DIR / 'shredder.gresource'
VERSION_PY = SHREDDER / '_version.py'
RMLINT_VERSION = GUI.parent / ".version"


def _read_dot_version(path: Path):
    try:
        return path.read_text(encoding="utf-8").split(' ', 1)[0]
    except OSError:
        return None


def _read_version_py():
    try:
        text = VERSION_PY.read_text(encoding="utf-8")
    except OSError:
        return None
    namespace = {}
    exec(text, namespace)
    return namespace.get("__version__")


def _generate_version_py(version):
    content = f'# Generated by setup.py -- do not edit, do not commit.\n' \
              f'__version__ = "{version}"\n'
    if not VERSION_PY.is_file() or VERSION_PY.read_text(encoding="utf-8") != content:
        VERSION_PY.write_text(content, encoding="utf-8")


def get_version():
    if version := _read_dot_version(RMLINT_VERSION):
        _generate_version_py(version)
        return version

    if version := _read_version_py():
        return version

    raise SystemExit(
        f"cannot determine version: no {RMLINT_VERSION} and no {VERSION_PY}."
    )


class build_gresource(Command):
    """Compile shredder.gresource.xml into the binary bundle."""

    description = __doc__
    user_options = []

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def get_source_files(self):
        deps = subprocess.check_output(
            ['glib-compile-resources', '--sourcedir', RESOURCE_DIR,
             '--generate-dependencies', GRESOURCE_XML], text=True).split()
        return [str(GRESOURCE_XML)] + deps

    def get_outputs(self):
        return [str(GRESOURCE)]

    def get_output_mapping(self):
        # The bundle is written into the source tree directly and referenced
        # in [tool.setuptools.package-data]
        return {}

    def run(self):
        subprocess.check_call([
            'glib-compile-resources',
            f'--sourcedir={RESOURCE_DIR}',
            f'--target={GRESOURCE}',
            str(GRESOURCE_XML),
        ])


build.sub_commands.insert(0, ("build_gresource", None))

setup(
    version=get_version(),
    cmdclass={"build_gresource": build_gresource},
)
