#!/usr/bin/env python3
"""Build-time hooks:

* resolve version
* compile the GResource bundle during the build
"""

import subprocess
import sys
from pathlib import Path

from setuptools import Command, setup
from setuptools.command.build import build

GUI = Path(__file__).parent
SHREDDER = GUI / 'shredder'
RESOURCE_DIR = SHREDDER / 'resources'
GRESOURCE_XML = RESOURCE_DIR / 'shredder.gresource.xml'
GRESOURCE = RESOURCE_DIR / 'shredder.gresource'
VERSION_PY = SHREDDER / '_version.py'
RMLINT_VERSION = GUI.parent / '.version'
SITE_SCONS = GUI.parent / 'site_scons'


def _ver_dot_version() -> tuple[str, str] | None:
    """(SemVer, PEP440) from .version, or None."""
    if str(SITE_SCONS) not in sys.path:
        sys.path.insert(0, str(SITE_SCONS))
    try:
        from rm_version import read_version
        version = read_version(RMLINT_VERSION)
    except (ImportError, OSError, ValueError):
        return None

    return str(version), version.pep440


def _ver_version_py() -> tuple[str, str] | None:
    """(SemVer, PEP440) from _version.py, or None."""
    try:
        text = VERSION_PY.read_text(encoding='utf-8')
    except OSError:
        return None

    ns = {'__builtins__': {}}
    exec(text, ns)
    try:
        return ns['version'], ns['pep440']
    except:
        return None


def _generate_version_py(version, pep440):
    content = (
        "# Generated by setup.py -- do not edit, do not commit.\n"
        f'__version__ = "{version}"\n'
        f'__pep440__ = "{pep440}"\n'
    )
    if not VERSION_PY.is_file() or VERSION_PY.read_text(encoding='utf-8') != content:
        VERSION_PY.write_text(content, encoding='utf-8')


def get_version():
    if version := _ver_dot_version():
        _generate_version_py(*version)
        return version[1]

    if version := _ver_version_py():
        return version[1]

    raise SystemExit(f"cannot determine version: no {RMLINT_VERSION} nor {VERSION_PY}.")


class build_gresource(Command):
    """Compile shredder.gresource.xml into the binary bundle."""

    description = __doc__
    user_options = []

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def get_source_files(self):
        deps = subprocess.check_output(
            ['glib-compile-resources', '--sourcedir', RESOURCE_DIR,
             '--generate-dependencies', GRESOURCE_XML], text=True).split()
        return [str(GRESOURCE_XML)] + deps

    def get_outputs(self):
        return [str(GRESOURCE)]

    def get_output_mapping(self):
        # The bundle is written into the source tree directly and referenced
        # in [tool.setuptools.package-data]
        return {}

    def run(self):
        subprocess.check_call([
            'glib-compile-resources',
            f'--sourcedir={RESOURCE_DIR}',
            f'--target={GRESOURCE}',
            str(GRESOURCE_XML),
        ])


build.sub_commands.insert(0, ("build_gresource", None))

setup(
    version=get_version(),
    cmdclass={"build_gresource": build_gresource},
)
