Import('env')
Import('VERSION_MAJOR')
Import('VERSION_MINOR')
Import('VERSION_PATCH')
Import('VERSION_NAME')
Import('create_uninstall_target')

import os
from pathlib import Path

from rm_build_support import ConfigHeaderBuilder, EmbedPayloadBuilder

ENV_KEYS = (
    # libraries
    'HAVE_LIBELF', 'HAVE_GIO_UNIX', 'HAVE_BLKID', 'HAVE_LIBINTL',
    # headers
    'HAVE_LINUX_LIMITS', 'HAVE_LINUX_FS_H', 'HAVE_BTRFS_H', 'HAVE_SYSMACROS_H',
    # syscalls / filesystem features
    'HAVE_FIEMAP', 'HAVE_XATTR', 'HAVE_LXATTR', 'HAVE_EXTATTR',
    'HAVE_POSIX_FADVISE', 'HAVE_SYSBLOCK', 'HAVE_UNAME',
    # large file support
    'HAVE_BIGFILES', 'HAVE_BIG_OFF_T', 'HAVE_STAT64',
    # cpu extensions
    'HAVE_MM_CRC32_U64', 'HAVE_BUILTIN_CPU_SUPPORTS',
    # language features
    'HAVE_C23_EMBED',
)

# XXX: remove this when we fully switch to C23+ only
MAYBE_EMBEDED_FORMATTERS = (
    ('formats/py.c', 'formats/py.py'),
    ('formats/sh.c', 'formats/sh.sh'),
)
FORMATTER_NAMES = {os.path.basename(src) for src, _ in MAYBE_EMBEDED_FORMATTERS}

CONFIG_VALUES = {
    **{key: env[key] for key in ENV_KEYS},
    'INSTALL_PREFIX': env['PREFIX'],
    'VERSION_MAJOR': VERSION_MAJOR,
    'VERSION_MINOR': VERSION_MINOR,
    'VERSION_PATCH': VERSION_PATCH,
    'VERSION_NAME': VERSION_NAME,
    'VERSION_GIT_REVISION': env['gitrev'].strip(),
}


env.Append(BUILDERS={
    'ConfigHeader': ConfigHeaderBuilder,
    'EmbedPayload': EmbedPayloadBuilder,
})

config = env.ConfigHeader('config.h', ['config.h.in', env.Value(CONFIG_VALUES)])

payloads = []
if not env['HAVE_C23_EMBED']:
    payloads = [env.EmbedPayload(f'{payload}.c.inc', payload)
                for _, payload in MAYBE_EMBEDED_FORMATTERS]

# XXX: remove this when we fully switch to C23+ only
formatter_env = env
if env['HAVE_C23_EMBED']:
    formatter_env = env.Clone(CCFLAGS=[
        flag for flag in env['CCFLAGS'] if not str(flag).startswith('-std=')
    ] + ['-std=c23'])

formatters = []
for source, payload in MAYBE_EMBEDED_FORMATTERS:
    obj = formatter_env.Object(source)
    # XXX: to be removed when/if https://github.com/SCons/scons/pull/4889 is merged
    env.Depends(obj, payload)
    formatters.append(obj)

# Listed unconditionally so that 'scons -c' also clears old c.inc files on a new compiler
env.Clean(formatters, [f'{payload}.c.inc' for _, payload in MAYBE_EMBEDED_FORMATTERS])

checksums = SConscript('checksums/SConscript', exports='env')

library = env.Library(
    '../rmlint',
    Glob('*.c') +
    checksums +
    formatters +
    [node for node in Glob('formats/*.c') if node.name not in FORMATTER_NAMES] +
    Glob('fts/*.c')
)

headers = Glob('*.h')
env.Depends(library, [config, *payloads])

# Disable this for now until someone
# announces interest in this.
INSTALL_LIBRARY = False

if INSTALL_LIBRARY:
    libdir = env['staged_prefix'] / env['LIBDIR']
    includedir = env['staged_prefix'] / 'include' / 'rmlint'

    if 'install' in COMMAND_LINE_TARGETS:
        env.Alias('install', env.Install(str(libdir), [library]))
        for header in headers:
            env.Alias('install', env.Install(str(includedir), [header]))

    if 'uninstall' in COMMAND_LINE_TARGETS:
        create_uninstall_target(env, libdir / Path(str(library[0])).name)

        for header in headers:
            create_uninstall_target(env, includedir / str(header))

Return('library')
