Import('env')
Import('VERSION_MAJOR')
Import('VERSION_MINOR')
Import('VERSION_PATCH')
Import('VERSION_NAME')
Import('create_uninstall_target')

import os

ENV_KEYS = (
    # libraries
    'HAVE_LIBELF', 'HAVE_GIO_UNIX', 'HAVE_BLKID', 'HAVE_SHA512', 'HAVE_LIBINTL',
    # headers
    'HAVE_LINUX_LIMITS', 'HAVE_LINUX_FS_H', 'HAVE_BTRFS_H', 'HAVE_SYSMACROS_H',
    # syscalls / filesystem features
    'HAVE_FIEMAP', 'HAVE_XATTR', 'HAVE_LXATTR', 'HAVE_POSIX_FADVISE',
    'HAVE_SYSBLOCK', 'HAVE_UNAME',
    # large file support
    'HAVE_BIGFILES', 'HAVE_BIG_OFF_T', 'HAVE_STAT64',
    # cpu extensions
    'HAVE_MM_CRC32_U64', 'HAVE_BUILTIN_CPU_SUPPORTS',
)

CONFIG_VALUES = {
    **{key: env[key] for key in ENV_KEYS},
    'INSTALL_PREFIX': GetOption('actual_prefix') or GetOption('prefix'),
    'VERSION_MAJOR': VERSION_MAJOR,
    'VERSION_MINOR': VERSION_MINOR,
    'VERSION_PATCH': VERSION_PATCH,
    'VERSION_NAME': VERSION_NAME,
    'VERSION_GIT_REVISION': env['gitrev'].strip(),
}


def build_config_template(target, source, env):
    template = source[0].get_text_contents()
    with open(target[0].get_abspath(), 'w') as handle:
        handle.write(template.format(**source[1].read()))


def prepare_c_source(text):
    # Prepare the Python source to be compatible with C-strings
    text = text.replace('\\', '\\\\')
    text = text.replace('"', '\\"')
    text = '\\n"\n"'.join(text.splitlines())

    return text


def embed_formatter_payload(target, source, placeholder):
    """Embed source[1] into the C template source[0]."""
    template = source[0].get_text_contents()
    payload = prepare_c_source(source[1].get_text_contents())

    with open(target[0].get_abspath(), 'w') as handle:
        handle.write(template.replace(placeholder, payload))


def build_python_formatter(target, source, env):
    embed_formatter_payload(target, source, '<<PYTHON_SOURCE>>')


def build_sh_formatter(target, source, env):
    embed_formatter_payload(target, source, '<<SH_SOURCE>>')


config = env.Command(
    'config.h', ['config.h.in', env.Value(CONFIG_VALUES)], build_config_template
)

py_formatter = env.Command(
    'formats/py.c', ['formats/py.c.in', 'formats/py.py'], build_python_formatter
)

sh_formatter = env.Command(
    'formats/sh.c', ['formats/sh.c.in', 'formats/sh.sh'], build_sh_formatter
)

checksums = SConscript('checksums/SConscript', exports='env')

library = env.Library(
    '../rmlint',
    Glob('*.c') +
    checksums +
    Glob('formats/*.c') +
    Glob('fts/*.c')
)

headers = Glob('*.h')
env.Depends(library, [config, py_formatter, sh_formatter])

# Disable this for now until someone
# announces interest in this.
INSTALL_LIBRARY = False

if 'install' in COMMAND_LINE_TARGETS and INSTALL_LIBRARY:
    env.Alias('install', env.Install('$PREFIX/' + GetOption('libdir'), [library]))
    for header in headers:
        env.Alias('install', env.Install('$PREFIX/include/rmlint', [header]))

if 'uninstall' in COMMAND_LINE_TARGETS and INSTALL_LIBRARY:
    create_uninstall_target(env, '$PREFIX/{}/{}'.format(
        GetOption('libdir'),
        os.path.basename(str(library[0]))
    ))

    for header in headers:
        create_uninstall_target(env, '$PREFIX/include/rmlint/' + str(header))

Return('library')
