Document: rmlint
Title: Debian rmlint Manual
Author: <insert document author here>
Abstract: This manual describes what rmlint is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rmlint/rmlint.sgml.gz

Format: postscript
Files: /usr/share/doc/rmlint/rmlint.ps.gz

Format: text
Files: /usr/share/doc/rmlint/rmlint.text.gz

Format: HTML
Index: /usr/share/doc/rmlint/html/index.html
Files: /usr/share/doc/rmlint/html/*.html
