Import('env')
Import('create_uninstall_target')
Import('VERSION_MAJOR')
Import('VERSION_MINOR')
Import('VERSION_PATCH')

import os
import subprocess

if env['HAVE_MSGFMT']:
    for src in env.Glob('*.po'):
        lang = os.path.basename(src.get_abspath())[:-3]
        mo = env.Command(f'{lang}.mo', src, 'msgfmt $SOURCE -o $TARGET')

        path = f'share/locale/{lang}/LC_MESSAGES/rmlint.mo'

        if 'install' in COMMAND_LINE_TARGETS:
            env.Alias('install', env.InstallAs('$staged_prefix/' + path, mo))

        if 'uninstall' in COMMAND_LINE_TARGETS:
            create_uninstall_target(env, '$PREFIX/' + path)


def xgettext():
    return subprocess.call(
        'xgettext --package-name rmlint -k_ -kN_ '
        f'--package-version {VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH} '
        '--default-domain rmlint '
        '--add-location=file '
        '--join-existing '
        '--output po/rmlint.pot '
        '--from-code UTF-8 '
        '$(find src lib -iname "*.[ch]") && '
        'sed -i "s/CHARSET/UTF-8/g" po/rmlint.pot',
        shell=True
    )


def xgettext_action(target=None, source=None, env=None):
    status = xgettext()
    if status:
        print('Error: xgettext failed')
        Exit(status)


def msgmerge():
    return subprocess.call(
        'set -e; '
        'for p in po/*.po; do '
        '  msgmerge --update --backup=none "$p" po/rmlint.pot; '
        'done',
        shell=True
    )


def msgmerge_action(target=None, source=None, env=None):
    status = msgmerge()
    if status:
        print('Error: msgmerge failed')
        Exit(status)


def gettext_action(target=None, source=None, env=None):
    status = xgettext()
    if status:
        print('Error: gettext failed while running xgettext')
        Exit(status)
    status = msgmerge()
    if status:
        print('Error: gettext failed while running msgmerge')
        Exit(status)


env.Alias(
    'xgettext',
    env.Command('xgettext', None, Action(xgettext_action, "Running xgettext"))
)
env.Alias(
    'msgmerge',
    env.Command('msgmerge', None, Action(msgmerge_action, "Running msgmerge"))
)
env.Alias(
    'gettext',
    env.Command('gettext', None, Action(gettext_action, "Running gettext"))
)
