#!/bin/sh
# This file was autowritten by rmlint
# rmlint was executed from: %s
# Your command line was: %s

USER='%s'
GROUP='%s'

##################################
# GENERAL LINT HANDLER FUNCTIONS #
##################################

handle_emptyfile() {
    echo 'Deleting empty file:' "$1"
    rm -f "$1"
}

handle_emptydir() {
    echo 'Deleting empty directory:' "$1"
    rmdir "$1"
}

handle_bad_symlink() {
    echo 'Deleting symlink pointing nowhere:' "$1"
    rm -f "$1"
}

handle_unstripped_binary() {
    echo 'Stripping debug symbols of:' "$1"
    strip -s "$1"
}

handle_bad_user_id() {
    echo 'chown' "$USER" "$1"
    chmod "$USER" "$1"
}

handle_bad_group_id() {
    echo 'chgrp' "$GROUP" "$1"
    chgrp "$GROUP" "$1"
}

handle_bad_user_and_group_id() {
    echo 'chmod' "$USER:$GROUP" "$1"
    chmod "$USER:$GROUP" "$1"
}

###############################
# DUPLICATE HANDLER FUNCTIONS #
###############################

cp_hardlink() {
    echo 'Hardlinking to original:' "$1"
    cp --remove-destination --archive --link "$2" "$1"
}

cp_symlink() {
    echo 'Symlinking to original:' "$1"
    touch -mr "$1" "$0"
    cp --remove-destination --archive --symbolic-link "$2" "$1"
    touch -mr "$0" "$1"
}

cp_reflink() {
    # reflink $1 to $2's data, preserving $1's  mtime
    echo 'Reflinking to original:' "$1"
    touch -mr "$1" "$0"
    cp --reflink=always "$2" "$1"
    touch -mr "$0" "$1"
}

user_command() {
    # You can define this function to do what you want:
    %s
}

remove_cmd() {
    echo 'Deleting:' "$1"
    rm -rf "$1"
}

##################
# OPTION PARSING #
##################

ask() {
    cat << EOF
This script will delete certain files rmlint found.
It is highly advisable to view the script first!

Execute this script with -d to disable this message
Hit enter to continue; CTRL-C to abort immediately
EOF
    read dummy_var
}

usage() {
    cat << EOF
usage: $0 options

OPTIONS:
-h      Show this message.
-d      Do not ask before running.
-x      Keep rmlint.sh; do note autodelete it.
EOF
}

DO_REMOVE=
DO_ASK=

while getopts "dhx" OPTION
do
  case $OPTION in
     h)
       usage
       exit 1
       ;;
     d)
       DO_ASK=false
       ;;
     x)
       DO_REMOVE=false
       ;;
  esac
done

if [ -z $DO_ASK ]
then
  usage
  ask
fi

######### START OF AUTOGENERATED OUTPUT #########


