#!/usr/bin/env python
# encoding: utf-8

Import('env')
Import('VERSION_MAJOR')
Import('VERSION_MINOR')
Import('VERSION_PATCH')


import os
import time
import tarfile


def tar_file(target, source, env):
    with tarfile.open(str(target[0]), "w:gz") as handle:
        for item in source:
            handle.add(str(item))


def build_man(target, source, env):
    rst_in_path = str(source[0])
    man_out_path = str(target[0])

    with open(rst_in_path, 'r') as handle:
        text = handle.read().format(
            VERSION='{}.{}.{} ({})'.format(
                VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, env['gitrev']
            ),
            DATE=time.strftime("%d-%m-%Y")
        )

    rst_meta_path = rst_in_path[:-4]
    with open(rst_meta_path, 'w') as handle:
        handle.write(text)

    os.system('rst2man "{s}" > "{t}"'.format(t=man_out_path, s=rst_meta_path))


env.AlwaysBuild(
    env.Alias('man',
        env.Command(
            'rmlint.1', 'rmlint.1.in.rst', build_man
        )
    )
)

env.AlwaysBuild(
    env.Command(
        'rmlint.1.gz', 'rmlint.1', tar_file
    )
)
