Import('env')
Import('create_uninstall_target')
Import('library')

programs = []
for progname in ['rmlint']:
    print('Building ' + progname)
    program = env.Program(f'../{progname}', [f'{progname}.c', library])

    env.Depends(program, [library])
    programs.append(program)

    if 'uninstall' in COMMAND_LINE_TARGETS:
        create_uninstall_target(env, '$PREFIX/bin/' + progname)


if 'install' in COMMAND_LINE_TARGETS:
    env.Alias(
        'install',
        env.InstallPerm('$staged_prefix/bin', programs, 0o755)
    )


env.Default(programs)
Return('programs')
