Import('env')

import platform


blake3 = Glob('blake3/*.[cS]')
blake3_machine = platform.machine().lower()

# Windows-only blake3 assembly files are vendored, ignore them for now.
blake3 = [f for f in blake3 if '_windows_' not in f.path]

if blake3_machine in ('x86_64', 'amd64'):
    # remove C intrinsics when we should use the assembly version
    blake3_intrinsics = (
        'blake3_sse2.c', 'blake3_sse41.c', 'blake3_avx2.c', 'blake3_avx512.c'
    )
    blake3 = [f for f in blake3 if f.name not in blake3_intrinsics]
else:
    # the assembly is x86-64-only
    blake3 = [f for f in blake3 if not f.path.endswith('.S')]

if blake3_machine != 'aarch64':
    blake3 = [f for f in blake3 if 'neon' not in f.path]

if not env['HAVE_AVX2']:
    print('Not compiling blake3 avx2 options')
    blake3 = [f for f in blake3 if 'avx2' not in f.path]
    env.Append(CCFLAGS=['-DBLAKE3_NO_AVX2'])

if not env['HAVE_AVX512F'] or not env['HAVE_AVX512VL']:
    print('Not compiling blake3 avx512 options')
    blake3 = [f for f in blake3 if 'avx512' not in f.path]
    env.Append(CCFLAGS=['-DBLAKE3_NO_AVX512'])

if not env['HAVE_SSE4_1']:
    print('Not compiling blake3 sse41 options')
    blake3 = [f for f in blake3 if 'sse41' not in f.path]
    env.Append(CCFLAGS=['-DBLAKE3_NO_SSE41'])

if not env['HAVE_SSE2']:
    print('Not compiling blake3 sse2 options')
    blake3 = [f for f in blake3 if 'sse2' not in f.path]
    env.Append(CCFLAGS=['-DBLAKE3_NO_SSE2'])

sources = (
    Glob('*.c') +
    Glob('xxhash/*.c') +
    Glob('blake2/*.c') +
    blake3 +
    Glob('sha3/*.c')
)

Return('sources')
