name: Build and test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RM_TS_DIR: "/tmp/rmlint-unit-testdir"
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: "Prepare build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            scons python3-sphinx gettext python3-setuptools \
            libblkid-dev libelf-dev libglib2.0-dev libjson-glib-dev \
            clang python3-pip python3-cffi python3-dev libffi-dev
          pip3 install -r tests/requirements.txt
          pip3 install -r docs/requirements.txt
          
      - name: "Build"
        # Todo: eventually run tests with valgrind (RM_TS_USE_VALGRIND)
        # Todo enable slow tests in pytest
        run: |
          scons config
          scons VERBOSE=1 DEBUG=1 O=release
        
      - name: "Check need for testing"
        # TODO also include skipping build but allow docs to be processed
        run: |
          if git diff --exit-code --name-only origin/$GITHUB_BASE_REF...$GITHUB_SHA ':!.gitignore' ':!docs' ':!*.md' ':!*.txt' ':!*.rst'; then
            echo "RUN_TEST=false" >> "$GITHUB_ENV"
            echo "RUN_TEST = false"
          else
            echo "RUN_TEST=true" >> "$GITHUB_ENV"
            echo "RUN_TEST = true"
          fi
  
      - name: "Prepare test environment"
        # TODO Ignore linter warning. See https://github.com/github/vscode-github-actions/issues/222        
        if: ${{ env.RUN_TEST == 'true' }}
        # The test suite is seriously disk-intensive. Given that linux
        #  instances hosted in GitHub have 16G of RAM available we will
        #  use it to speed up the run.
        run: |
          sudo mkdir "${RM_TS_DIR}"
          sudo mount -o size=12G,nr_inodes=0 -t tmpfs tmpfs "${RM_TS_DIR}"

      - name: "Test it"
        if: ${{ env.RUN_TEST == 'true' }}
        run: |
          RM_TS_PEDANTIC=0 python -m pytest -s -v

      - name: CoW tests - BTRFS
        if: ${{ env.RUN_TEST == 'true' }}
        shell: bash
        run: |
          sudo umount "${RM_TS_DIR}"
          sudo modprobe brd rd_nr=1 rd_size=12582912
          sudo mkfs.btrfs -f /dev/ram0
          sudo mount /dev/ram0 "${RM_TS_DIR}"
          sudo chmod 0777 "${RM_TS_DIR}"

          RM_TS_PEDANTIC=0 python -m pytest -s -v tests/test_mains/test_is_reflink.py
          RM_TS_PEDANTIC=0 python -m pytest -s -v tests/test_mains/test_dedupe.py
      - name: Build ZFS
        if: ${{ env.RUN_TEST == 'true' }}
        shell: bash
        run: |
          sudo apt install alien autoconf automake build-essential debhelper-compat dh-autoreconf dh-dkms dh-python dkms fakeroot gawk git libaio-dev libattr1-dev libblkid-dev libcurl4-openssl-dev libelf-dev libffi-dev libpam0g-dev libssl-dev libtirpc-dev libtool libudev-dev linux-headers-generic parallel po-debconf python3 python3-all-dev python3-cffi python3-dev python3-packaging python3-setuptools python3-sphinx uuid-dev zlib1g-dev
          git clone -b zfs-2.4-release --single-branch https://github.com/openzfs/zfs.git
          cd ./zfs
          sh autogen.sh
          ./configure
          make -s -j$(nproc) --no-print-directory --silent pkg-utils pkg-kmod
          sudo dpkg -i *.deb
          # Update order of directories to search for modules, otherwise
          #   Ubuntu will load kernel-shipped ones.
          sudo sed -i.bak 's/updates/extra updates/' /etc/depmod.d/ubuntu.conf
          sudo depmod
          sudo modprobe zfs
          echo "ZFS versions installed:"
          sudo zfs -V
          echo "Bclone enabled: $(cat /sys/module/zfs/parameters/zfs_bclone_enabled)"
      - name: CoW tests - ZFS
        if: ${{ env.RUN_TEST == 'true' }}
        shell: bash
# TODO: change to blkdiscard when the runner will be running 6.10+ kernel.
        run: |
          sudo umount "${RM_TS_DIR}"
          sudo rmmod brd
          sudo modprobe brd rd_nr=1 rd_size=12582912

          sudo zpool create -m "${RM_TS_DIR}" rmlint ram0

          sudo chmod 0777 "${RM_TS_DIR}"

          RM_TS_PEDANTIC=0 python -m pytest -s -v tests/test_mains/test_is_reflink.py

      - name: "Cleanup"
        if: ${{ env.RUN_TEST == 'true' }}
        run: |
          sudo umount "${RM_TS_DIR}"
          sudo rmdir "${RM_TS_DIR}"
