name: FreeBSD

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore: &skip
      - "docs/**"
      - "gui/**"
      - '**.md'
      - '**.rst'
      - '.gitignore'
  push:
    branches:
      - master
      - develop
    paths-ignore: *skip
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - id: prepare-hash
        run: echo "hash=$(sha256sum ci/freebsd/prepare.sh | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Build and test
        uses: vmactions/freebsd-vm@v1
        with:
          mem: 12288
          copyback: false
          cache-after-prepare: true
          prepare: |
            # prepare-hash: ${{ steps.prepare-hash.outputs.hash }}
            ./ci/freebsd/prepare.sh
          run: |
            ./ci/freebsd/build-and-test.sh
