name: macOS

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore: &skip
      - '**.md'
      - '.gitignore'
  push:
    branches:
      - master
      - develop
    paths-ignore: *skip
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: macos-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_ENV_HINTS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        id: python
        with:
          python-version: '>=3.12'

      - name: Prepare build environment
        run: |
          brew install --quiet \
            scons pkgconf glib json-glib
          pip install -r tests/requirements.txt -r docs/requirements.txt \
            setuptools build installer

      - name: Build
        env:
          PYTHON: ${{ steps.python.outputs.python-path }}
        run: |
          scons --without-gettext --show-config VERBOSE=1 DEBUG=1 O=release

      - name: Test
        run: |
          RM_TS_ALWAYS_CLEAN=1 pytest
