name: Multi-distro

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  multi-distro-build:
    name: Build (${{ matrix.build.tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          # EL
          - tag: "almalinux:10"
            installcmd: "dnf install -y"
            pkgs: "gcc python3-scons glib2-devel json-glib-devel"
          - tag: "quay.io/centos/centos:stream10"
            installcmd: "dnf install -y"
            pkgs: "gcc python3-scons glib2-devel json-glib-devel"
          # Alpine
          - tag: "alpine:latest"
            installcmd: "apk add --no-cache"
            pkgs: "build-base pkgconf scons glib-dev json-glib-dev elfutils-dev py3-sphinx"
          # ArchLinux
          - tag: "archlinux:latest"
            installcmd: "pacman -Syu --noconfirm"
            pkgs: "base-devel json-glib scons"
          # Debian
          - tag: "debian:stable"
            env: "DEBIAN_FRONTEND=noninteractive"
            installcmd: "apt-get update && apt-get install -y --no-install-recommends"
            pkgs: "gcc scons pkg-config gettext libblkid-dev libelf-dev libffi-dev libglib2.0-dev libjson-glib-dev python3-sphinx"
          - tag: "debian:testing"
            env: "DEBIAN_FRONTEND=noninteractive"
            installcmd: "apt-get update && apt-get install -y --no-install-recommends"
            pkgs: "gcc scons pkg-config gettext libblkid-dev libelf-dev libffi-dev libglib2.0-dev libjson-glib-dev python3-sphinx"
          # Fedora
          - tag: "fedora:latest"
            installcmd: "dnf install -y"
            pkgs: "gcc python3-scons pkgconf-pkg-config glib2-devel json-glib-devel"
          - tag: "fedora:rawhide"
            installcmd: "dnf install -y"
            pkgs: "gcc python3-scons pkgconf-pkg-config glib2-devel json-glib-devel"
          # OpenSUSE
          - tag: "opensuse/leap:latest"
            installcmd: "zypper -n install"
            pkgs: "gcc scons pkgconf glib2-devel json-glib-devel libelf-devel libblkid-devel"
          - tag: "opensuse/tumbleweed:latest"
            installcmd: "zypper -n install"
            pkgs: "gcc scons pkgconf glib2-devel json-glib-devel libelf-devel libblkid-devel"
          # Ubuntu
          - tag: "ubuntu:resolute"
            env: "DEBIAN_FRONTEND=noninteractive"
            installcmd: "apt-get update && apt-get install -y --no-install-recommends"
            pkgs: "gcc scons pkg-config gettext libblkid-dev libelf-dev libffi-dev libglib2.0-dev libjson-glib-dev python3-sphinx"
          - tag: "ubuntu:rolling"
            env: "DEBIAN_FRONTEND=noninteractive"
            installcmd: "apt-get update && apt-get install -y --no-install-recommends"
            pkgs: "gcc scons pkg-config gettext libblkid-dev libelf-dev libffi-dev libglib2.0-dev libjson-glib-dev python3-sphinx"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: "Build on ${{ matrix.build.tag }}"
        run: >
          echo "
            export UNUSED_VAR_SO_THIS_CMD_IS_NEVER_EMPTY= ${{ matrix.build.env }} 
            ${{ matrix.build.installcmd }} ${{ matrix.build.pkgs }}
            cd /build
            scons config
            scons VERBOSE=1 DEBUG=1 O=release
            exit
          " | docker run --rm -v "$PWD:/build" "${{ matrix.build.tag }}" sh
